export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  SOCIAL_CALLBACK: "/social-callback",
  DASHBOARD: "/dashboard",
  RECIPES: "/recipes",
  MEAL_PLANNER: "/meal-planner",
  INVENTORY: "/inventory",
  SHOPPING_LIST: "/shopping-list",
  NUTRITION: "/nutrition",
  HOUSEHOLD: "/household",
  PROFILE: "/profile",
  SETTINGS: "/settings",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_EMAIL: "/verify-email",
  SHARED_RECIPE: "/recipes/share/:shareId",
} as const;
